import { initializeApp } from "https://www.gstatic.com/firebasejs/11.8.1/firebase-app.js";
import { getAuth, GoogleAuthProvider, signInWithPopup, signOut, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/11.8.1/firebase-auth.js";
import { getFirestore, collection, doc, getDoc, setDoc, addDoc, updateDoc, onSnapshot, query, orderBy, serverTimestamp } from "https://www.gstatic.com/firebasejs/11.8.1/firebase-firestore.js";
import { getStorage, ref, uploadBytes, getDownloadURL } from "https://www.gstatic.com/firebasejs/11.8.1/firebase-storage.js";
import { firebaseConfig } from "./firebase-config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),storage=getStorage(app),$=s=>document.querySelector(s);let user,profile,reports=[],stop;
const guidance={Low:"Check and assist the student on-site.",Medium:"Escort the student to the medical block.",High:"Coordinate directly with doctors or bring medical help immediately."};
function say(message,error=false){const e=$("#app-message")||$("#auth-message");e.textContent=message;e.className=`status-message ${error?"error":"success"}`;}function role(){return profile?.role||"Student"}function permit(a){return ({submit:role()==="Student",task:role()==="Volunteer",resolve:role()==="Doctor"})[a]===true}function fmt(v){return v?.toDate?v.toDate().toLocaleString():"Just now"}
async function profileFor(current){const target=doc(db,"users",current.uid),snap=await getDoc(target);if(!snap.exists()){const selected=$("input[name='role']:checked").value;await setDoc(target,{email:current.email,displayName:current.displayName||current.email,role:selected,createdAt:serverTimestamp()});return {role:selected,email:current.email};}return snap.data();}
async function googleLogin(){const b=$("#google-sign-in");b.disabled=true;b.textContent="Signing in…";try{await signInWithPopup(auth,new GoogleAuthProvider());}catch(e){$("#auth-message").textContent=e.code==="auth/popup-closed-by-user"?"Sign-in window closed. Try again.":"Google sign-in failed. Confirm this domain is authorized in Firebase Authentication.";}finally{b.disabled=false;b.textContent="Continue with Google";}}
function listen(){stop?.();stop=onSnapshot(query(collection(db,"reports"),orderBy("createdAt","desc")),snap=>{reports=snap.docs.map(d=>({id:d.id,...d.data()}));render();},()=>say("Could not load reports. Check Firestore Rules and connection.",true));}
function badge(text,kind){const e=document.createElement("span");e.className=`badge ${kind}-${String(text).toLowerCase().replaceAll(" ","-")}`;e.textContent=text;return e}function line(k,v){const x=document.createElement("div"),a=document.createElement("dt"),b=document.createElement("dd");x.className="detail-row";a.textContent=k;b.textContent=v;x.append(a,b);return x}
async function task(id,value){if(!permit("task"))return say("Only volunteers can update helper tasks.",true);try{await updateDoc(doc(db,"reports",id),{helperStatus:value,updatedAt:serverTimestamp()});say("Volunteer task updated.");}catch{say("Task update was blocked by Firestore Rules.",true)}}
async function resolve(id){const r=reports.find(x=>x.id===id);if(!permit("resolve")||!r||r.emergencyType!=="Medical"||r.reportStatus!=="Pending")return say("Only doctors can resolve pending medical reports.",true);if(!confirm(`Mark ${r.reportId} as resolved?`))return;try{await updateDoc(doc(db,"reports",id),{reportStatus:"Resolved",resolvedBy:user.email,resolvedAt:serverTimestamp(),updatedAt:serverTimestamp()});say("Medical report resolved.");}catch{say("Resolution was blocked by Firestore Rules.",true)}}
function render(){if(!profile)return;let list=reports.filter(r=>role()==="Student"?r.submittedByUid===user.uid:role()==="Doctor"?r.emergencyType==="Medical":true);$("#report-count").textContent=`${list.length} reports`;const sum=$("#summary-cards");sum.replaceChildren();[["Total",list.length],["Pending",list.filter(r=>r.reportStatus==="Pending").length],["High",list.filter(r=>r.severity==="High").length],["Resolved",list.filter(r=>r.reportStatus==="Resolved").length]].forEach(([k,v])=>{const e=document.createElement("div");e.className="summary-card";e.textContent=`${v} ${k}`;sum.append(e)});const out=$("#reports");out.replaceChildren();if(!list.length){const e=document.createElement("p");e.className="empty-state";e.textContent="No reports to display.";return out.append(e)}list.forEach(r=>{const c=document.createElement("article"),top=document.createElement("div"),h=document.createElement("h3"),tags=document.createElement("div"),dl=document.createElement("dl");c.className=`report-card ${r.severity==="High"?"high-priority":""}`;top.className="card-topline";h.className="report-id";h.textContent=r.reportId;tags.className="badges";tags.append(badge(`${r.severity} severity`,"severity"),badge(r.reportStatus,"report"),badge(r.helperStatus,"helper"));top.append(h,tags);dl.className="report-details";dl.append(line("Type",r.emergencyType),line("Location",r.location),line("Description",r.description),line("Submitted",fmt(r.createdAt)),line("Response guidance",guidance[r.severity]));if(r.attachmentUrl){const a=document.createElement("a");a.href=r.attachmentUrl;a.target="_blank";a.rel="noopener";a.textContent="Open submitted image";const d=document.createElement("dd");d.append(a);dl.append(d)}c.append(top,dl);if(role()==="Volunteer"){const s=document.createElement("select");["Not yet","On it","Done"].forEach(v=>{const o=document.createElement("option");o.textContent=v;o.selected=v===r.helperStatus;s.append(o)});s.addEventListener("change",()=>task(r.id,s.value));c.append(s)}if(role()==="Doctor"&&r.reportStatus==="Pending"){const b=document.createElement("button");b.className="resolve-button";b.textContent="Mark as Resolved";b.addEventListener("click",()=>resolve(r.id));c.append(b)}out.append(c)});}
async function submit(e){e.preventDefault();if(!permit("submit"))return say("Only students can submit reports.",true);const type=$("#type").value,description=$("#description").value.trim(),location=$("#location").value,severity=$("input[name='severity']:checked")?.value,file=$("#attachment").files[0];if(!type||!location||!severity||description.length<5||description.length>300)return say("Provide type, location, severity, and a 5–300 character description.",true);const b=$("#submit-report");b.disabled=true;b.textContent="Saving…";try{let attachmentUrl=null;if(file){if(file.size>5*1024*1024||!file.type.startsWith("image/"))throw new Error("Choose an image under 5 MB.");const path=`report-attachments/${user.uid}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`,target=ref(storage,path);await uploadBytes(target,file,{contentType:file.type});attachmentUrl=await getDownloadURL(target)}const now=new Date(),reportId=`ER-${now.getFullYear()}${String(now.getMonth()+1).padStart(2,"0")}${String(now.getDate()).padStart(2,"0")}-${Math.random().toString(36).slice(2,8).toUpperCase()}`;await addDoc(collection(db,"reports"),{reportId,emergencyType:type,description,location,severity,reportStatus:"Pending",helperStatus:"Not yet",submittedByUid:user.uid,submittedByEmail:user.email,attachmentUrl,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});e.target.reset();$("#count").textContent="0";say(`Emergency report ${reportId} submitted.`);}catch(err){say(err.message||"Could not save report. Check Firebase configuration and Rules.",true)}finally{b.disabled=false;b.textContent="Report Emergency";}}
onAuthStateChanged(auth,async current=>{if(!current){user=null;profile=null;stop?.();$("#sign-in-view").hidden=false;$("#app-view").hidden=true;return}user=current;try{profile=await profileFor(current);$("#sign-in-view").hidden=true;$("#app-view").hidden=false;$("#role-label").textContent=`${role()} dashboard`;$("#user-label").textContent=`${current.displayName||current.email} · ${role()}`;$("#student-form").hidden=role()!=="Student";listen()}catch{say("Could not load your Firebase profile. Check Firestore Rules.",true)}});
$("#google-sign-in").addEventListener("click",googleLogin);$("#sign-out").addEventListener("click",()=>signOut(auth));$("#report-form").addEventListener("submit",submit);$("#description").addEventListener("input",e=>$("#count").textContent=e.target.value.length);

