export type DemoPerson = { id?: string; isCurrent?: boolean; name: string; handle: string; branch: string; year: string; skills: string[]; availableDays: number[]; freshness: string; bio: string; interests?: string[]; isOpenToWork?: boolean; verified?: boolean };
export type DemoProject = { id: string; title: string; type: string; timezone: string; commitment: string; roles: number; categories: string[]; description: string; openRoles: string[]; ownerId?: string; ownerName?: string; institution?: string; createdAtMs?: number; status?: "Open" | "Forming" | "Active" };

export const campusName = "SRM Institute of Science and Technology, Kattankulathur";
export const campusShortName = "SRM University";

export const studentInterests = ["AI & Machine Learning", "Climate Tech", "Healthtech", "Fintech", "Robotics", "EdTech", "Game Development", "Cybersecurity", "Social Impact", "Research", "Entrepreneurship", "Open Source"] as const;

export const engineeringStreams = [
  ["CSE", "Computer Science / IT"], ["ECE", "Electronics & Communication"],
  ["EEE", "Electrical Engineering"], ["MECH", "Mechanical Engineering"],
  ["CIVIL", "Civil Engineering"], ["CHEMICAL", "Chemical Engineering"],
  ["BIOTECH", "Biotechnology / Biomedical"], ["AEROSPACE", "Aerospace Engineering"],
  ["OTHER", "Cross-disciplinary / Other"],
] as const;

export const people: DemoPerson[] = [
  { name: "Priya Nair", handle: "priya-nair", branch: "CSE", year: "3rd Year", skills: ["React", "Next.js", "UI/UX"], availableDays: [0,1,2,4,5], freshness: "synced 3 hours ago", bio: "Frontend builder who loves turning complex ideas into clear product experiences." },
  { name: "Arjun Mehta", handle: "arjun-mehta", branch: "ECE", year: "3rd Year", skills: ["IoT", "Embedded Systems", "Python"], availableDays: [1,2,3,5], freshness: "manually set 2 days ago", bio: "ECE student building practical connected devices." },
  { name: "Aisha Khan", handle: "aisha-khan", branch: "CSE", year: "2nd Year", skills: ["Data Science", "Python", "Pandas"], availableDays: [0,2,3,4], freshness: "synced yesterday", bio: "Data explorer looking for meaningful climate and health projects." },
  { name: "Rohan Iyer", handle: "rohan-iyer", branch: "MECH", year: "4th Year", skills: ["CAD/CAM", "Robotics", "Manufacturing"], availableDays: [1,3,4,6], freshness: "manually set 1 week ago", bio: "Mechanical engineer with a robotics prototype habit." },
  { name: "Meera Das", handle: "meera-das", branch: "BIOTECH", year: "1st Year", skills: ["Bioinformatics", "Data Analysis", "Research"], availableDays: [0,1,4,5], freshness: "synced 5 hours ago", bio: "Curious biotech learner excited by collaborative research." },
  { name: "Vikram Rao", handle: "vikram-rao", branch: "EEE", year: "4th Year", skills: ["Renewable Energy", "Control Systems", "IoT"], availableDays: [2,3,4,5], freshness: "manually set 3 days ago", bio: "Power systems enthusiast pursuing clean-energy prototypes." },
  { name: "Kavya Menon", handle: "kavya-menon", branch: "CIVIL", year: "2nd Year", skills: ["Structural Design", "Environmental Engineering", "CAD"], availableDays: [0,2,5], freshness: "synced 6 hours ago", bio: "Civil engineering student focused on sustainable public infrastructure." },
  { name: "Daniel Joseph", handle: "daniel-joseph", branch: "CHEMICAL", year: "3rd Year", skills: ["Process Engineering", "Materials Science", "Data Analysis"], availableDays: [1,3,5,6], freshness: "manually set yesterday", bio: "Process engineering student interested in cleaner industrial systems." },
  { name: "Sara Ahmed", handle: "sara-ahmed", branch: "AEROSPACE", year: "4th Year", skills: ["Aerodynamics", "Avionics", "Python"], availableDays: [0,1,3,4], freshness: "synced 2 hours ago", bio: "Aerospace builder exploring flight systems and simulation." },
  { name: "Neel Shah", handle: "neel-shah", branch: "OTHER", year: "1st Year", skills: ["Product Management", "Technical Writing", "Business & Marketing"], availableDays: [2,4,6], freshness: "manually set today", bio: "Cross-disciplinary organizer who helps technical teams ship clearly." },
  { name: "Ishita Verma", handle: "ishita-verma", branch: "CSE", year: "4th Year", skills: ["Cybersecurity", "Node.js", "Cloud"], availableDays: [0,2,4,5], freshness: "calendar synced today", bio: "Security-minded backend engineer who enjoys practical threat modelling." },
  { name: "Karthik Subramanian", handle: "karthik-subramanian", branch: "ECE", year: "2nd Year", skills: ["Computer Vision", "Robotics", "C++"], availableDays: [1,3,5], freshness: "calendar synced yesterday", bio: "Robotics student connecting visual intelligence with reliable hardware." },
];
export const projects: DemoProject[] = [
  { id: "campus-carbon-map", title: "Campus Carbon Map", type: "Hackathon", timezone: "Asia/Kolkata", commitment: "8 hrs/week", roles: 3, categories: ["Data Science", "UI/UX Design", "Web Development"], description: "Turn campus energy data into actions students can take.", openRoles: ["Data Scientist", "Product Designer", "Frontend Developer"], status: "Forming" },
  { id: "mindful-study-companion", title: "Mindful Study Companion", type: "Startup", timezone: "Asia/Kolkata", commitment: "10 hrs/week", roles: 2, categories: ["Mobile App Development", "Product Management", "AI/ML"], description: "A supportive planning companion for study teams.", openRoles: ["Mobile Developer", "ML Engineer"], status: "Open" },
  { id: "smart-irrigation-lab", title: "Smart Irrigation Lab", type: "Research", timezone: "Asia/Kolkata", commitment: "6 hrs/week", roles: 2, categories: ["IoT", "Embedded Systems", "Data Analysis"], description: "Field-ready sensors for water-efficient growing.", openRoles: ["Embedded Engineer", "Data Analyst"], status: "Forming" },
  { id: "accessible-transit", title: "Accessible Transit", type: "Coursework", timezone: "Asia/Kolkata", commitment: "5 hrs/week", roles: 1, categories: ["UI/UX Design", "Web Development"], description: "An inclusive route-planning prototype for local transport.", openRoles: ["Accessibility Designer"], status: "Open" },
  { id: "hostel-energy-optimizer", title: "Hostel Energy Optimizer", type: "Research", timezone: "Asia/Kolkata", commitment: "7 hrs/week", roles: 2, categories: ["Machine Learning", "Electrical Systems"], description: "Forecast hostel demand and reduce avoidable electricity use.", openRoles: ["ML Researcher", "Power Systems Analyst"], status: "Open" },
  { id: "srm-open-courseware", title: "SRM Open Courseware", type: "Open Source", timezone: "Asia/Kolkata", commitment: "4 hrs/week", roles: 3, categories: ["Next.js", "Technical Writing", "Accessibility"], description: "A searchable, accessible collection of student-created learning resources.", openRoles: ["Frontend Engineer", "Content Editor", "Accessibility Tester"], status: "Active" },
  { id: "drone-rescue-grid", title: "Drone Rescue Grid", type: "Hackathon", timezone: "Asia/Kolkata", commitment: "12 hrs/week", roles: 3, categories: ["Computer Vision", "Avionics", "Mapping"], description: "Coordinate small drones during simulated campus emergency response.", openRoles: ["Vision Engineer", "Flight Systems Engineer", "GIS Developer"], status: "Forming" },
  { id: "lab-safety-assistant", title: "Lab Safety Assistant", type: "Coursework", timezone: "Asia/Kolkata", commitment: "5 hrs/week", roles: 2, categories: ["Computer Vision", "Chemical Safety"], description: "Detect missing protective equipment and surface clear lab reminders.", openRoles: ["Computer Vision Developer", "Safety Researcher"], status: "Open" },
  { id: "peer-skill-exchange", title: "Peer Skill Exchange", type: "Startup", timezone: "Asia/Kolkata", commitment: "8 hrs/week", roles: 2, categories: ["Product Management", "Mobile App Development"], description: "Help SRM students exchange short, practical peer-learning sessions.", openRoles: ["Product Lead", "Mobile Developer"], status: "Forming" },
  { id: "water-quality-sentinel", title: "Water Quality Sentinel", type: "Research", timezone: "Asia/Kolkata", commitment: "6 hrs/week", roles: 3, categories: ["IoT", "Biotechnology", "Data Analysis"], description: "Combine low-cost sensors and campus research to track water quality.", openRoles: ["Sensor Engineer", "Biotech Researcher", "Data Analyst"], status: "Open" },
  { id: "inclusive-club-events", title: "Inclusive Club Events", type: "Open Source", timezone: "Asia/Kolkata", commitment: "3 hrs/week", roles: 2, categories: ["Accessibility", "UI/UX Design"], description: "Reusable tools that help campus clubs publish accessible event information.", openRoles: ["Accessibility Designer", "Frontend Contributor"], status: "Active" },
  { id: "solar-kart-telemetry", title: "Solar Kart Telemetry", type: "Hackathon", timezone: "Asia/Kolkata", commitment: "10 hrs/week", roles: 2, categories: ["Embedded Systems", "Data Visualization"], description: "Live telemetry and diagnostics for an SRM student solar kart prototype.", openRoles: ["Embedded Developer", "Data Visualization Engineer"], status: "Forming" },
];
